In [39]:
import sys
import json
import requests
 
API_URL = 'https://evolve-ai-labs-pty-ltd.dynamic.orm.datarobot.com/predApi/v1.0/deployments/{deployment_id}/predictionsUnstructured'    # noqa
API_KEY = ''
DATAROBOT_KEY = ''
 
DEPLOYMENT_ID = '681c20830e0350e49a789e78'

data = '{"num_matrices": 2, "row_count": 3, "col_count": 3}'

headers = {
    # 'Content-Type': '{};charset={}'.format(mimetype, charset),
    'Content-Type': 'application/json',
    'Authorization': 'Bearer {}'.format(API_KEY),
    'DataRobot-Key': DATAROBOT_KEY,
}
 
url = API_URL.format(deployment_id=DEPLOYMENT_ID)

predictions_response = requests.post(
    url,
    data=data,
    headers=headers,
)
predictions_response.content

b'"[[[65,51,81],[44,20,53],[72,59,65]],[[19,74,8],[70,69,64],[45,81,14]]]"'

In [43]:
matrices = json.loads(json.loads(predictions_response.content))
for mat in matrices:
    print(np.array(mat))

[[65 51 81]
 [44 20 53]
 [72 59 65]]
[[19 74  8]
 [70 69 64]
 [45 81 14]]
